export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const ADD_EVENT_LOADING = 'ADD_EVENT_LOADING';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE';

export const GET_EVENTS_LOADING = 'GET_EVENTS_LOADING';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

export const GET_POLICE_OFFICERS_LOADING = 'GET_POLICE_OFFICERS_LOADING';
export const GET_POLICE_OFFICERS_SUCCESS = 'GET_POLICE_OFFICERS_SUCCESS';
export const GET_POLICE_OFFICERS_FAILURE = 'GET_POLICE_OFFICERS_FAILURE';

export const GET_CITIZENS_LOADING = 'GET_CITIZENS_LOADING';
export const GET_CITIZENS_SUCCESS = 'GET_CITIZENS_SUCCESS';
export const GET_CITIZENS_FAILURE = 'GET_CITIZENS_FAILURE';

export const UPDATE_EVENT_LOADING = 'UPDATE_EVENT_LOADING';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE';

export const DELETE_EVENT_LOADING = 'DELETE_EVENT_LOADING';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';

export const UPDATE_COORDINATE_LOADING = 'UPDATE_COORDINATE_LOADING';
export const UPDATE_COORDINATE_SUCCESS = 'UPDATE_COORDINATE_SUCCESS';
export const UPDATE_COORDINATE_FAILURE = 'UPDATE_COORDINATE_FAILURE';

export const SET_NEWEST_EVENT = 'SET_NEWEST_EVENT';